[clone_directories]
# default directory for cloing if no matchers are found
default = "~/src/github.com/{{ .Owner }}/{{ .Name }}"
# matchers are checked in order, first match is used.
# supports glob style matches
matchers = [
  { match = "business/*", dir = "~/src/mealie-recipes/{{ .Name }}" },
  { match = "mealie-recipes/*", dir = "~/src/mealie-recipes/{{ .Name }}" },
]


[logs]
file = "./.temp/repomgr.log"
level = "debug"
color = true

[database]
file = "./.temp/repomgr.db"
params = "_pragma=busy_timeout=2000&_pragma=journal_mode=WAL&_fk=1"

[[sources]]
type = "github"
username = "hay-kot"
organizations = ["mealie-recipes"]
# token properties have special syntax for environment variables
token = "env:REPOMGR_GH_TOKEN"

[key_bindings]
# if not ::<cmd> then it's a shell command to be executed
# go-templates are supported
"o" = "open {{ .CloneURL }}"
# clones the repository in the project_dir
"c" = ":GitClone"
# pulls the project in the directory, if not already present
# clone as well
"p" = ":GitPull"
# exits the program and prints only the clone URL
"enter" = ":Exit {{ .CloneURL }}"
