version: "3"

env:
  REPOMGR_LOG_FILE: "./.temp/repomgr.log"
  REPOMGR_CONFIG: "./.repomgr.toml"

tasks:
  run:
    desc: Runs the main application and supports passing CLI args
    cmds:
      - go run *.go {{ .CLI_ARGS }}
    silent: false

  logs:
    desc: tails the log file for the application
    cmds:
      - tail -f ${REPOMGR_LOG_FILE}

  build:
    desc: Builds the backend binary
    cmds:
      - goreleaser build --snapshot --rm-dist

  fmt:
    desc: Runs go fmt on the backend
    cmds:
      - gofumpt -w .

  test:
    desc: Runs all go tests using gotestsum - supports passing gotestsum args
    cmds:
      - go test -v {{ .CLI_ARGS }} ./...

  test:watch:
    desc: Runs all go tests using gotestsum in watch mode
    cmds:
      - gotestsum --watch -- -v ./...

  coverage:
    desc: Runs all go tests with -race flag and generates a coverage report
    cmds:
      - go test -race -coverprofile=coverage.out -covermode=atomic ./... -v -cover
    silent: true

  tidy:
    desc: Runs go mod tidy on the backend
    cmds:
      - go mod tidy

  lint:
    desc: Runs golangci-lint
    cmds:
      - golangci-lint run ./...

  pr:
    desc: Runs all go test and lint related tasks for PRs
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: test

  gen:
    desc: Generates code using sqlc
    cmds:
      - sqlc generate
