// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Repository struct {
	ID          int64
	RemoteID    string
	Name        string
	Username    string
	Description string
	HtmlUrl     string
	CloneUrl    string
	CloneSshUrl string
	IsFork      bool
	ForkUrl     string
}

type RepositoryArtifact struct {
	ID           int64
	DataType     string
	Data         []byte
	RepositoryID int64
}
