// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Repository struct {
	ID          int64
	RemoteID    string
	Name        string
	Username    string
	Description string
	CloneUrl    string
	CloneSshUrl string
	IsFork      bool
}

type RepositoryArtifact struct {
	ID           int64
	Type         string
	Data         []byte
	RepositoryID int64
}
